name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal code example
      description: |
        Please provide a minimal example that reproduces the issue.
        If the code is too long, feel free to put it in a public gist and link it in the issue.
      placeholder: |
        ```python
        # Your code here
        ```
    validations:
      required: true

  - type: textarea
    id: version-info
    attributes:
      label: Version info
      description: |
        Please paste the output of `scxpand.__version__` and `session_info.show()` (if available).
        You can install session-info with `pip install session-info`.
      placeholder: |
        scxpand version:

        ```
        # Output of session_info.show()
        ```
    validations:
      required: true
